---
- name: Running MYSQL Database as Docker Container using Ansible.
  hosts: all
  become: true


  vars:
    db_volume: db_data
    
    
  tasks:

  - name: Launch mysql database container
    docker_container:
      name: db
      image: mysql:5.7
      volumes:
        - "{{ db_volume }}:/var/lib/mysql"
      restart: true
      env:
        MYSQL_ROOT_PASSWORD: test
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test
      ports:
        - "33306:3306"
